# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mcb_editor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MCBWidget(object):
    def setupUi(self, MCBWidget):
        MCBWidget.setObjectName("MCBWidget")
        MCBWidget.resize(453, 477)
        self.gridLayout = QtWidgets.QGridLayout(MCBWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_tab = QtWidgets.QTabWidget(MCBWidget)
        self.widget_tab.setObjectName("widget_tab")
        self.tab_text = QtWidgets.QWidget()
        self.tab_text.setObjectName("tab_text")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_text)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vlayout_text = QtWidgets.QVBoxLayout()
        self.vlayout_text.setObjectName("vlayout_text")
        self.lbl_onlyalphanumeric = QtWidgets.QLabel(self.tab_text)
        self.lbl_onlyalphanumeric.setObjectName("lbl_onlyalphanumeric")
        self.vlayout_text.addWidget(self.lbl_onlyalphanumeric)
        self.txtEdit_input = QtWidgets.QTextEdit(self.tab_text)
        self.txtEdit_input.setObjectName("txtEdit_input")
        self.vlayout_text.addWidget(self.txtEdit_input)
        self.hlayout_symbols = QtWidgets.QHBoxLayout()
        self.hlayout_symbols.setObjectName("hlayout_symbols")
        self.lbl_specialsymbols = QtWidgets.QLabel(self.tab_text)
        self.lbl_specialsymbols.setObjectName("lbl_specialsymbols")
        self.hlayout_symbols.addWidget(self.lbl_specialsymbols)
        self.cbox_symbols = QtWidgets.QComboBox(self.tab_text)
        self.cbox_symbols.setObjectName("cbox_symbols")
        self.hlayout_symbols.addWidget(self.cbox_symbols)
        self.btn_insert_symbol = QtWidgets.QPushButton(self.tab_text)
        self.btn_insert_symbol.setObjectName("btn_insert_symbol")
        self.hlayout_symbols.addWidget(self.btn_insert_symbol)
        self.vlayout_text.addLayout(self.hlayout_symbols)
        self.lbl_preview = QtWidgets.QLabel(self.tab_text)
        self.lbl_preview.setObjectName("lbl_preview")
        self.vlayout_text.addWidget(self.lbl_preview)
        self.graphics_preview = QtWidgets.QGraphicsView(self.tab_text)
        self.graphics_preview.setObjectName("graphics_preview")
        self.vlayout_text.addWidget(self.graphics_preview)
        self.verticalLayout_2.addLayout(self.vlayout_text)
        self.widget_tab.addTab(self.tab_text, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_settings)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_character = QtWidgets.QLabel(self.tab_settings)
        self.lbl_character.setObjectName("lbl_character")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_character)
        self.lbl_pose = QtWidgets.QLabel(self.tab_settings)
        self.lbl_pose.setObjectName("lbl_pose")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_pose)
        self.lbl_voicefile = QtWidgets.QLabel(self.tab_settings)
        self.lbl_voicefile.setObjectName("lbl_voicefile")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_voicefile)
        self.lbl_bgmfile = QtWidgets.QLabel(self.tab_settings)
        self.lbl_bgmfile.setObjectName("lbl_bgmfile")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_bgmfile)
        self.lbl_boxpos = QtWidgets.QLabel(self.tab_settings)
        self.lbl_boxpos.setObjectName("lbl_boxpos")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_boxpos)
        self.lbl_boxtyping = QtWidgets.QLabel(self.tab_settings)
        self.lbl_boxtyping.setObjectName("lbl_boxtyping")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_boxtyping)
        self.lbl_boxarrow = QtWidgets.QLabel(self.tab_settings)
        self.lbl_boxarrow.setObjectName("lbl_boxarrow")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_boxarrow)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.widget_tab.addTab(self.tab_settings, "")
        self.gridLayout.addWidget(self.widget_tab, 1, 0, 1, 1)
        self.hlayout_fileinfo = QtWidgets.QHBoxLayout()
        self.hlayout_fileinfo.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hlayout_fileinfo.setObjectName("hlayout_fileinfo")
        self.lbl_file_fileinfo = QtWidgets.QLabel(MCBWidget)
        self.lbl_file_fileinfo.setObjectName("lbl_file_fileinfo")
        self.hlayout_fileinfo.addWidget(self.lbl_file_fileinfo)
        self.txt_file_purpose = QtWidgets.QTextBrowser(MCBWidget)
        self.txt_file_purpose.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_file_purpose.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txt_file_purpose.setObjectName("txt_file_purpose")
        self.hlayout_fileinfo.addWidget(self.txt_file_purpose)
        self.lbl_file_textnumber = QtWidgets.QLabel(MCBWidget)
        self.lbl_file_textnumber.setObjectName("lbl_file_textnumber")
        self.hlayout_fileinfo.addWidget(self.lbl_file_textnumber)
        self.sbox_text_number = QtWidgets.QSpinBox(MCBWidget)
        self.sbox_text_number.setMaximumSize(QtCore.QSize(40, 20))
        self.sbox_text_number.setObjectName("sbox_text_number")
        self.hlayout_fileinfo.addWidget(self.sbox_text_number)
        self.gridLayout.addLayout(self.hlayout_fileinfo, 0, 0, 1, 1)

        self.retranslateUi(MCBWidget)
        self.widget_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MCBWidget)

    def retranslateUi(self, MCBWidget):
        _translate = QtCore.QCoreApplication.translate
        MCBWidget.setWindowTitle(_translate("MCBWidget", "MCB Text Editor"))
        self.lbl_onlyalphanumeric.setText(_translate("MCBWidget", "Only alphanumeric (A-Z, 0-9) characters"))
        self.lbl_specialsymbols.setText(_translate("MCBWidget", "Special Symbols:"))
        self.btn_insert_symbol.setText(_translate("MCBWidget", "Insert"))
        self.lbl_preview.setText(_translate("MCBWidget", "Preview:"))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.tab_text), _translate("MCBWidget", "Text"))
        self.lbl_character.setText(_translate("MCBWidget", "Character: "))
        self.lbl_pose.setText(_translate("MCBWidget", "Pose:"))
        self.lbl_voicefile.setText(_translate("MCBWidget", "Voice File: "))
        self.lbl_bgmfile.setText(_translate("MCBWidget", "BGM File:"))
        self.lbl_boxpos.setText(_translate("MCBWidget", "Box Position:"))
        self.lbl_boxtyping.setText(_translate("MCBWidget", "Box Typing:"))
        self.lbl_boxarrow.setText(_translate("MCBWidget", "Box Arrow:"))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.tab_settings), _translate("MCBWidget", "Settings"))
        self.lbl_file_fileinfo.setText(_translate("MCBWidget", "File Info:"))
        self.lbl_file_textnumber.setText(_translate("MCBWidget", "Text No."))

