# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 417)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupFile = QtWidgets.QGroupBox(self.centralwidget)
        self.groupFile.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupFile.setObjectName("groupFile")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupFile)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboFiles = QtWidgets.QComboBox(self.groupFile)
        self.comboFiles.setObjectName("comboFiles")
        self.horizontalLayout.addWidget(self.comboFiles)
        self.btnOpenCloseFile = QtWidgets.QPushButton(self.groupFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenCloseFile.sizePolicy().hasHeightForWidth())
        self.btnOpenCloseFile.setSizePolicy(sizePolicy)
        self.btnOpenCloseFile.setObjectName("btnOpenCloseFile")
        self.horizontalLayout.addWidget(self.btnOpenCloseFile)
        self.verticalLayout_2.addWidget(self.groupFile)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupText = QtWidgets.QGroupBox(self.centralwidget)
        self.groupText.setObjectName("groupText")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupText)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupText)
        self.label.setMinimumSize(QtCore.QSize(40, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 40))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinCurrentText = QtWidgets.QSpinBox(self.groupText)
        self.spinCurrentText.setMinimumSize(QtCore.QSize(40, 0))
        self.spinCurrentText.setMaximumSize(QtCore.QSize(40, 40))
        self.spinCurrentText.setObjectName("spinCurrentText")
        self.horizontalLayout_2.addWidget(self.spinCurrentText)
        self.label_2 = QtWidgets.QLabel(self.groupText)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 40))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lblTotalTexts = QtWidgets.QLabel(self.groupText)
        self.lblTotalTexts.setMinimumSize(QtCore.QSize(25, 0))
        self.lblTotalTexts.setMaximumSize(QtCore.QSize(25, 40))
        self.lblTotalTexts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblTotalTexts.setLineWidth(1)
        self.lblTotalTexts.setTextFormat(QtCore.Qt.RichText)
        self.lblTotalTexts.setObjectName("lblTotalTexts")
        self.horizontalLayout_2.addWidget(self.lblTotalTexts)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEditor = QtWidgets.QTextEdit(self.groupText)
        self.textEditor.setMaximumSize(QtCore.QSize(1000, 400))
        self.textEditor.setObjectName("textEditor")
        self.verticalLayout.addWidget(self.textEditor)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btnSave = QtWidgets.QPushButton(self.groupText)
        self.btnSave.setEnabled(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_7.addWidget(self.btnSave)
        self.btnRevert = QtWidgets.QPushButton(self.groupText)
        self.btnRevert.setObjectName("btnRevert")
        self.horizontalLayout_7.addWidget(self.btnRevert)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4.addWidget(self.groupText)
        self.groupExtraData = QtWidgets.QGroupBox(self.centralwidget)
        self.groupExtraData.setMaximumSize(QtCore.QSize(400, 150000))
        self.groupExtraData.setObjectName("groupExtraData")
        self.formLayout = QtWidgets.QFormLayout(self.groupExtraData)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupExtraData)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textFilename = QtWidgets.QLineEdit(self.groupExtraData)
        self.textFilename.setEnabled(False)
        self.textFilename.setReadOnly(True)
        self.textFilename.setClearButtonEnabled(False)
        self.textFilename.setObjectName("textFilename")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textFilename)
        self.label_6 = QtWidgets.QLabel(self.groupExtraData)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupExtraData)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_10 = QtWidgets.QLabel(self.groupExtraData)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupExtraData)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupExtraData)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_9 = QtWidgets.QLabel(self.groupExtraData)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_13 = QtWidgets.QLabel(self.groupExtraData)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboVoice = QtWidgets.QComboBox(self.groupExtraData)
        self.comboVoice.setObjectName("comboVoice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboVoice)
        self.comboBGM = QtWidgets.QComboBox(self.groupExtraData)
        self.comboBGM.setObjectName("comboBGM")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBGM)
        self.spinCameraAngle = QtWidgets.QSpinBox(self.groupExtraData)
        self.spinCameraAngle.setObjectName("spinCameraAngle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinCameraAngle)
        self.comboCharacter = QtWidgets.QComboBox(self.groupExtraData)
        self.comboCharacter.setObjectName("comboCharacter")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboCharacter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinMugshot = QtWidgets.QSpinBox(self.groupExtraData)
        self.spinMugshot.setObjectName("spinMugshot")
        self.horizontalLayout_3.addWidget(self.spinMugshot)
        self.textMugshotDesc = QtWidgets.QLineEdit(self.groupExtraData)
        self.textMugshotDesc.setEnabled(False)
        self.textMugshotDesc.setObjectName("textMugshotDesc")
        self.horizontalLayout_3.addWidget(self.textMugshotDesc)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.comboMugshotPos = QtWidgets.QComboBox(self.groupExtraData)
        self.comboMugshotPos.setObjectName("comboMugshotPos")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboMugshotPos)
        self.comboTextPos = QtWidgets.QComboBox(self.groupExtraData)
        self.comboTextPos.setObjectName("comboTextPos")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboTextPos)
        self.checkArrow = QtWidgets.QCheckBox(self.groupExtraData)
        self.checkArrow.setObjectName("checkArrow")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkArrow)
        self.checkCloseTop = QtWidgets.QCheckBox(self.groupExtraData)
        self.checkCloseTop.setObjectName("checkCloseTop")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkCloseTop)
        self.checkStopBGM = QtWidgets.QCheckBox(self.groupExtraData)
        self.checkStopBGM.setObjectName("checkStopBGM")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.checkStopBGM)
        self.checkTyping = QtWidgets.QCheckBox(self.groupExtraData)
        self.checkTyping.setObjectName("checkTyping")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.checkTyping)
        self.horizontalLayout_4.addWidget(self.groupExtraData)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.groupPreview = QtWidgets.QGroupBox(self.centralwidget)
        self.groupPreview.setObjectName("groupPreview")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupPreview)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsPreview = QtWidgets.QLabel(self.groupPreview)
        self.graphicsPreview.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsPreview.setMaximumSize(QtCore.QSize(1000, 1000))
        self.graphicsPreview.setObjectName("graphicsPreview")
        self.verticalLayout_3.addWidget(self.graphicsPreview)
        self.verticalLayout_2.addWidget(self.groupPreview)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MegaManX8 Text Editor by RainfallPianist <V1.0>"))
        self.groupFile.setTitle(_translate("MainWindow", "File"))
        self.btnOpenCloseFile.setText(_translate("MainWindow", "Open File"))
        self.groupText.setTitle(_translate("MainWindow", "Text Editor"))
        self.label.setText(_translate("MainWindow", "Current Text"))
        self.label_2.setText(_translate("MainWindow", "out of"))
        self.lblTotalTexts.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#aa0000;\">42</span></p></body></html>"))
        self.btnSave.setText(_translate("MainWindow", "Save Changes"))
        self.btnRevert.setText(_translate("MainWindow", "Revert"))
        self.groupExtraData.setTitle(_translate("MainWindow", "Extra Data Editor"))
        self.label_5.setText(_translate("MainWindow", "Filename"))
        self.label_6.setText(_translate("MainWindow", "Voice"))
        self.label_7.setText(_translate("MainWindow", "BGM"))
        self.label_10.setText(_translate("MainWindow", "Character"))
        self.label_11.setText(_translate("MainWindow", "Mugshot"))
        self.label_12.setText(_translate("MainWindow", "Mugshot Position"))
        self.label_9.setText(_translate("MainWindow", "Camera Angle"))
        self.label_13.setText(_translate("MainWindow", "Text Position"))
        self.checkArrow.setText(_translate("MainWindow", "Show an Arrow"))
        self.checkCloseTop.setText(_translate("MainWindow", "Close Top Dialogue"))
        self.checkStopBGM.setText(_translate("MainWindow", "Stop all BGM"))
        self.checkTyping.setText(_translate("MainWindow", "Type One Letter At A Time"))
        self.groupPreview.setTitle(_translate("MainWindow", "Preview"))
        self.graphicsPreview.setText(_translate("MainWindow", "PREVIEW WILL GO HERE"))

